### ISSUE TITLE
[0.8.3b] NPE @ CompositeTab.verifyText()

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#110]
java.lang.NullPointerException
	at org.nschmidt.ldparteditor.data.Vertex.<init>(Vertex.java:82)
	at org.nschmidt.ldparteditor.composites.compositetab.CompositeTab$3.verifyText(CompositeTab.java:414)

**Comment by nilsschmidt1337** [comment]
Closed with commit 5c78e79.
