### ISSUE TITLE
[OpenGL 3] ConcurrentModificationException on CSG reset

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#1105]
```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.base/java.util.HashMap$KeyIterator.next(Unknown Source)
	at java.base/java.util.AbstractCollection.addAll(Unknown Source)
	at java.base/java.util.HashSet.<init>(Unknown Source)
	at org.nschmidt.ldparteditor.data.GDataCSG.resetCSG(GDataCSG.java:148)
	at org.nschmidt.ldparteditor.data.GL33ModelRenderer.lambda$renderThread$3(GL33ModelRenderer.java:600)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit [a9ffcf8](https://github.com/nilsschmidt1337/ldparteditor/commit/a9ffcf8e1b2f3206ef2ee20d14653b0cddd1f335).
