### ISSUE TITLE
[0.8.4b] IllegalArgumentException @ Primitive.sort()

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#112]
Exception in thread "main" java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(Unknown Source)
	at java.util.TimSort.mergeAt(Unknown Source)
	at java.util.TimSort.mergeCollapse(Unknown Source)
	at java.util.TimSort.sort(Unknown Source)
	at java.util.Arrays.sort(Unknown Source)
	at java.util.ArrayList.sort(Unknown Source)
	at java.util.Collections.sort(Unknown Source)
	at org.nschmidt.ldparteditor.data.Primitive.sort(Primitive.java:227)
	at org.nschmidt.ldparteditor.composites.primitive.CompositePrimitive.load(CompositePrimitive.java:1030)
	at org.nschmidt.ldparteditor.composites.primitive.CompositePrimitive.loadPrimitives(CompositePrimitive.java:554)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DDesign.createContents(Editor3DDesign.java:1990)
	at org.eclipse.jface.window.Window.create(Window.java:431)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:316)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:298)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:39)

**Comment by nilsschmidt1337** [comment]
Closed with commit f003bcf.
