### ISSUE TITLE
SWTException: Wiget is Disposed, when dragging and dropping text editor tabs (@ CompositeTab.java)

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#126]
A rare but important bug.

org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.getDisplay(Unknown Source)
	at org.nschmidt.ldparteditor.composites.compositetab.CompositeTab$14.widgetSelected(CompositeTab.java:1119)

**Comment by nilsschmidt1337** [comment]
Closed with commit e724169.
