### ISSUE TITLE
NPE @ Copy

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#283]
[LDPartEditor RELEASE 0.8.11b @ SWT v4527 OS win32]
java.lang.NullPointerException
	at org.nschmidt.ldparteditor.data.VM99Clipboard$1.compare(VM99Clipboard.java:443)
	at org.nschmidt.ldparteditor.data.VM99Clipboard$1.compare(VM99Clipboard.java:1)
	at java.util.TimSort.countRunAndMakeAscending(Unknown Source)
	at java.util.TimSort.sort(Unknown Source)
	at java.util.Arrays.sort(Unknown Source)
	at java.util.ArrayList.sort(Unknown Source)
	at java.util.Collections.sort(Unknown Source)
	at org.nschmidt.ldparteditor.data.VM99Clipboard.copy(VM99Clipboard.java:344)
	at org.nschmidt.ldparteditor.data.VertexManager.copy(VertexManager.java:1)
	at org.nschmidt.ldparteditor.composites.Composite3D$7.widgetSelected(Composite3D.java:607)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:5373)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:372)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:39)

**Comment by nilsschmidt1337** [comment]
Closed with commit 1e9b108.
