### ISSUE TITLE
NPE @ Open *.dat File (3D Editor)

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#286]
```
java.lang.NullPointerException
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow$12.widgetSelected(Editor3DWindow.java:718)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:5633)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:372)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:39)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit  ea894a4.
