### ISSUE TITLE
NPE @ ColourChange

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#290]
```
[LDPartEditor RELEASE 0.8.9 @ SWT v4527 OS win32]
java.lang.NullPointerException
	at org.nschmidt.ldparteditor.data.VM00Base.linker(VM00Base.java:1732)
	at org.nschmidt.ldparteditor.data.VM19ColourChanger.changeColour(VM19ColourChanger.java:309)
	at org.nschmidt.ldparteditor.data.VM19ColourChanger.changeColour(VM19ColourChanger.java:240)
	at org.nschmidt.ldparteditor.data.VM19ColourChanger.colourChangeSelection(VM19ColourChanger.java:111)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DDesign$8$2.widgetSelected(Editor3DDesign.java:2936)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:5346)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:372)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:39)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit e8ad1ef.
