### ISSUE TITLE
NPE @ VM00Base.delete()

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#319]
```
[LDPartEditor RELEASE 0.8.15 @ SWT v4527 OS win32]
java.lang.NullPointerException
	at org.nschmidt.ldparteditor.data.VM00Base.delete(VM00Base.java:1694)
	at org.nschmidt.ldparteditor.state.KeyStateManager.setStates(KeyStateManager.java:258)
	at org.nschmidt.ldparteditor.composites.Composite3D$58.handleEvent(Composite3D.java:1329)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.wmKeyDown(Unknown Source)
	at org.eclipse.swt.widgets.Control.WM_KEYDOWN(Unknown Source)
	at org.eclipse.swt.widgets.Canvas.WM_KEYDOWN(Unknown Source)
	at org.eclipse.swt.widgets.Control.windowProc(Unknown Source)
	at org.eclipse.swt.widgets.Canvas.windowProc(Unknown Source)
	at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:5672)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:377)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:39)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit 1f209d4.
