### ISSUE TITLE
NPE @ ColourChange

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#320]
```
[LDPartEditor RELEASE 0.8.15 @ SWT v4527 OS win32]
java.lang.NullPointerException
	at org.nschmidt.ldparteditor.data.VM19ColourChanger.colourChangeSelection(VM19ColourChanger.java:200)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DDesign$11$2.widgetSelected(Editor3DDesign.java:3061)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:5672)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:377)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:39)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit 328204e.
