### ISSUE TITLE
NPE @ Hide And Show

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#322]
```
[LDPartEditor RELEASE 0.8.15 @ SWT v4527 OS win32]
java.lang.NullPointerException
	at org.nschmidt.ldparteditor.data.VM11HideShow.hideSelection(VM11HideShow.java:56)
	at org.nschmidt.ldparteditor.data.VM12IntersectorAndIsecalc.hideSelection(VM12IntersectorAndIsecalc.java:1)
	at org.nschmidt.ldparteditor.data.VM20Manipulator.hideSelection(VM20Manipulator.java:1)
	at org.nschmidt.ldparteditor.data.VM21Merger.hideSelection(VM21Merger.java:1)
	at org.nschmidt.ldparteditor.data.VM25RectangleSnap.hideSelection(VM25RectangleSnap.java:1)
	at org.nschmidt.ldparteditor.data.VertexManager.hideSelection(VertexManager.java:1)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow$76.widgetSelected(Editor3DWindow.java:3015)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:5672)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:377)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:39)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit 3a1ef64.
