### ISSUE TITLE
NPE @ Round

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#324]
```
[LDPartEditor RELEASE 0.8.15 @ SWT v4527 OS win32]
java.lang.NullPointerException
	at java.util.TreeMap.getEntry(Unknown Source)
	at java.util.TreeMap.containsKey(Unknown Source)
	at java.util.TreeMap$KeySet.contains(Unknown Source)
	at org.nschmidt.ldparteditor.data.Rounder.round(Rounder.java:60)
	at org.nschmidt.ldparteditor.shells.editortext.EditorTextWindow$32.widgetSelected(EditorTextWindow.java:892)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:5672)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:377)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:39)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit 9329e17.
