### ISSUE TITLE
Widget is disposed @ org.nschmidt.ldparteditor.widgets.TreeItem (Cache error)

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#362]
```
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.checkWidget(Unknown Source)
	at org.eclipse.swt.widgets.TreeItem.setImage(Unknown Source)
	at org.nschmidt.ldparteditor.widgets.TreeItem.build(TreeItem.java:240)  <---- Error is here.
	at org.nschmidt.ldparteditor.widgets.Tree.build(Tree.java:114)
	at org.nschmidt.ldparteditor.data.DatFile.parseForError(DatFile.java:862)
	at org.nschmidt.ldparteditor.composites.compositetab.CompositeTab.parseForErrorAndHints(CompositeTab.java:1432)
	at org.nschmidt.ldparteditor.data.ColourChanger.changeColour(ColourChanger.java:40)
	at org.nschmidt.ldparteditor.shells.editortext.EditorTextDesign$1.widgetSelected(EditorTextDesign.java:307)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:5976)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:377)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:39)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit 9cfa74a.
