### ISSUE TITLE
The new SashForm throws (sometimes) an exception on resize

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#367]
...introduced with the new feature to combine the text and 3D editor on one window.

### It only occurs if I activate/deactivate a ruler once.

_Ben_ from the eclipse.org forums:
> I had similiar problems after updating to newer SWT versions for cases where
> is was wrongly using a GridData in a FillLayout. Make sure that in any case
> the **Layout of the Parent** matches the LayoutData of all Childs.

```
java.lang.ClassCastException: org.eclipse.swt.layout.GridData cannot be cast to org.eclipse.swt.layout.FillData
	at org.eclipse.swt.layout.FillLayout.computeChildSize(Unknown Source)
	at org.eclipse.swt.layout.FillLayout.computeSize(Unknown Source)
	at org.eclipse.swt.widgets.Composite.computeSize(Unknown Source)
	at org.eclipse.swt.custom.SashFormLayout.computeSize(Unknown Source)
	at org.eclipse.swt.widgets.Composite.computeSize(Unknown Source)
	at org.eclipse.swt.custom.SashFormLayout.computeSize(Unknown Source)
	at org.eclipse.swt.widgets.Composite.computeSize(Unknown Source)
	at org.eclipse.swt.layout.GridData.computeSize(Unknown Source)
	at org.eclipse.swt.layout.GridLayout.layout(Unknown Source)
	at org.eclipse.swt.layout.GridLayout.layout(Unknown Source)
	at org.eclipse.swt.widgets.Composite.updateLayout(Unknown Source)
	at org.eclipse.swt.widgets.Composite.WM_SIZE(Unknown Source)
	at org.eclipse.swt.widgets.Control.windowProc(Unknown Source)
	at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
	at org.eclipse.swt.internal.win32.OS.DefWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Unknown Source)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Unknown Source)
	at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Unknown Source)
	at org.eclipse.swt.widgets.Control.windowProc(Unknown Source)
	at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
	at org.eclipse.swt.internal.win32.OS.EndDeferWindowPos(Native Method)
	at org.eclipse.swt.widgets.Composite.resizeChildren(Unknown Source)
	at org.eclipse.swt.widgets.Composite.resizeChildren(Unknown Source)
	at org.eclipse.swt.widgets.Composite.setResizeChildren(Unknown Source)
	at org.eclipse.swt.widgets.Composite.WM_SIZE(Unknown Source)
	at org.eclipse.swt.widgets.Control.windowProc(Unknown Source)
	at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
	at org.eclipse.swt.internal.win32.OS.DefWindowProcW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Unknown Source)
	at org.eclipse.swt.widgets.Scrollable.callWindowProc(Unknown Source)
	at org.eclipse.swt.widgets.Control.WM_WINDOWPOSCHANGED(Unknown Source)
	at org.eclipse.swt.widgets.Control.windowProc(Unknown Source)
	at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
	at org.eclipse.swt.internal.win32.OS.SetWindowPos(Native Method)
	at org.eclipse.swt.widgets.Widget.SetWindowPos(Unknown Source)
	at org.eclipse.swt.widgets.Control.setBounds(Unknown Source)
	at org.eclipse.swt.widgets.Composite.setBounds(Unknown Source)
	at org.eclipse.swt.widgets.Control.setBounds(Unknown Source)
	at org.eclipse.swt.widgets.Control.setBounds(Unknown Source)
	at org.eclipse.swt.widgets.Control.setBounds(Unknown Source)
	at org.eclipse.swt.custom.SashForm.onDragSash(Unknown Source)
	at org.eclipse.swt.custom.SashForm$1.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendSelectionEvent(Unknown Source)
	at org.eclipse.swt.widgets.Sash.WM_LBUTTONUP(Unknown Source)
	at org.eclipse.swt.widgets.Control.windowProc(Unknown Source)
	at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:6009)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:377)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:39)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit 4a505b2.
