### ISSUE TITLE
"Toggle Comment" / "Toggle !TEXMAP" can cause data corruption when it is toggled on the last line of a file.

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#403]
**NPE @ HistoryManager, caused by Toggle Comment / Toggle !TEXMAP**

```
[DEBUG 0.8.21] @org.nschmidt.ldparteditor.data.HistoryManager$1  The HistoryManager cycle was throwing an exception :(
[ERROR 0.8.21] @org.nschmidt.ldparteditor.data.HistoryManager$1
java.lang.NullPointerException
	at org.nschmidt.ldparteditor.data.HistoryManager$1.run(HistoryManager.java:110)
	at java.lang.Thread.run(Unknown Source)
```

1. Toggle comment on the last line of the file
2. Insert something
3. Last line disappears?

```
java.lang.NullPointerException
	at org.nschmidt.ldparteditor.data.DatFile.addHistory(DatFile.java:1801)
	at org.nschmidt.ldparteditor.data.VM00Base.syncWithTextEditors(VM00Base.java:213)
	at org.nschmidt.ldparteditor.data.VM00Base.setModified(VM00Base.java:176)
	at org.nschmidt.ldparteditor.data.VM99Clipboard.paste(VM99Clipboard.java:697)
	at org.nschmidt.ldparteditor.data.VertexManager.paste(VertexManager.java:1)
	at org.nschmidt.ldparteditor.composites.Composite3D$10.widgetSelected(Composite3D.java:551)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:6147)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:377)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:39)
```

They do not update the draw chain tail??

**Comment by nilsschmidt1337** [comment]
Closed with commit 9f455a3.
