### ISSUE TITLE
Minor bug: The primitive area renderer tried to render after the 3D window was closed.

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#558]
```
Exception in thread "main" org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.checkWidget(Unknown Source)
	at org.eclipse.swt.opengl.GLCanvas.isCurrent(Unknown Source)
	at org.nschmidt.ldparteditor.opengl.OpenGLRendererPrimitives33.drawScene(OpenGLRendererPrimitives33.java:64)
	at org.nschmidt.ldparteditor.composites.primitive.CompositePrimitive$3$1.run(CompositePrimitive.java:229)
	at org.eclipse.swt.widgets.Display.runTimer(Unknown Source)
	at org.eclipse.swt.widgets.Display.messageProc(Unknown Source)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.swt.widgets.Display.release(Unknown Source)
	at org.eclipse.swt.graphics.Device.dispose(Unknown Source)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:6088)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:394)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:39)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit 1339d82.
