### ISSUE TITLE
NPE related to the CompositePrimitive class

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#59]
java.lang.NullPointerException
	at org.nschmidt.ldparteditor.composites.primitive.CompositePrimitive$4.handleEvent(CompositePrimitive.java:232)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:4590)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:290)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:39)

**Comment by nilsschmidt1337** [comment]
Closed with commit a1a8eb9.
