### ISSUE TITLE
IllegalStateException in RayTracer

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#61]
Exception in thread "Thread-2524" java.lang.IllegalStateException: Zero length vector
	at org.lwjgl.util.vector.Vector.normalise(Vector.java:91)
	at org.nschmidt.ldparteditor.opengl.OpenGLRenderer$1.run(OpenGLRenderer.java:617)
	at java.lang.Thread.run(Unknown Source)

**Comment by nilsschmidt1337** [comment]
Closed with commit b54ff29.
