### ISSUE TITLE
Catmull-Clark Subdivision: Divide by zero

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#626]
```
java.lang.ArithmeticException: Division undefined
	at java.math.BigDecimal.divide(Unknown Source)
	at org.nschmidt.ldparteditor.data.VM16Subdivide.subdivideCatmullClark(VM16Subdivide.java:115)
	at org.nschmidt.ldparteditor.data.VM20Manipulator.subdivideCatmullClark(VM20Manipulator.java:1)
```
Revision
https://github.com/nilsschmidt1337/ldparteditor/tree/2faf4936981174137e0dd664958ecadca94116d2

**Comment by nilsschmidt1337** [comment]
Closed with commit 86920df.
