### ISSUE TITLE
(uncritical) Linux: SWTException on current display (Widget is disposed)

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#634]
This bug was introduced with the new CSG engine.

```
Exception in thread "main" org.eclipse.swt.SWTException: Failed to execute runnable org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.checkWidget(Unknown Source)
	at org.eclipse.swt.widgets.MenuItem.getSelection(Unknown Source)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.loadSelectorSettings(Editor3DWindow.java:8273)
	at org.nschmidt.ldparteditor.helpers.composite3d.GuiStatusManager.updateStatus(GuiStatusManager.java:104)
	at org.nschmidt.csg.CSG.lambda$10(CSG.java:499)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.swt.widgets.Display.release(Unknown Source)
	at org.eclipse.swt.graphics.Device.dispose(Unknown Source)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:6228)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:394)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:39)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit e9aa6cf.
