### ISSUE TITLE
NullPointerException @ double click on text editor problem tree

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#637]
```
java.lang.NullPointerException
	at org.nschmidt.ldparteditor.composites.compositetab.CompositeTab$16.handleEvent(CompositeTab.java:1645)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:6221)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:394)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:39)
```

Revision:
https://github.com/nilsschmidt1337/ldparteditor/tree/e9aa6cfa7b2caaa3c934c8eff3418bf83938ff29

**Comment by nilsschmidt1337** [comment]
Closed with commit 3fc600d.
