### ISSUE TITLE
NPE @ DatFile.addHistory():1973 , v0.8.37 (Log file investigation #1)

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#674]
```
java.lang.NullPointerException
	at org.nschmidt.ldparteditor.data.DatFile.addHistory(DatFile.java:1973)
	at org.nschmidt.ldparteditor.data.VM00Base.syncWithTextEditors(VM00Base.java:214)
	at org.nschmidt.ldparteditor.data.VM00Base.setModified(VM00Base.java:177)
	at org.nschmidt.ldparteditor.data.tools.Merger.mergeTo(Merger.java:87)
	at org.nschmidt.ldparteditor.data.VM21Merger.merge(VM21Merger.java:284)
	at org.nschmidt.ldparteditor.state.KeyStateManager.setStates(KeyStateManager.java:693)
	at org.nschmidt.ldparteditor.composites.Composite3D$83.handleEvent(Composite3D.java:1531)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1130)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1126)
	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1547)
	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4962)
	at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:364)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4843)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:359)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5178)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2560)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3815)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:6220)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:394)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:39)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit b2b5ccb.
