### ISSUE TITLE
NPE @ VM00Base.syncWithTextEditors():264, v0.8.37 (Log file investigation #1)

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#675]
```
java.lang.NullPointerException
	at org.nschmidt.ldparteditor.data.VM00Base$1.run(VM00Base.java:264)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit 72c29b1.
