### ISSUE TITLE
StringIndexOutOfBoundsException @ CompositeTab.verifyText():480, v0.8.37 (Log file investigation #1)

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#676]
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -194
	at java.lang.String.substring(Unknown Source)
	at org.nschmidt.ldparteditor.composites.compositetab.CompositeTab$4.verifyText(CompositeTab.java:480)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:274)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:802)
	at org.eclipse.swt.custom.StyledText.modifyContent(StyledText.java:7323)
	at org.eclipse.swt.custom.StyledText.sendKeyEvent(StyledText.java:8203)
	at org.eclipse.swt.custom.StyledText.doDelete(StyledText.java:2594)
	at org.eclipse.swt.custom.StyledText.invokeAction(StyledText.java:7147)
	at org.eclipse.swt.custom.StyledText.handleKey(StyledText.java:6007)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6034)
	at org.eclipse.swt.custom.StyledText.lambda$installListeners$1(StyledText.java:5732)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1130)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1126)
	at org.eclipse.swt.widgets.Widget.wmKeyDown(Widget.java:1849)
	at org.eclipse.swt.widgets.Control.WM_KEYDOWN(Control.java:5216)
	at org.eclipse.swt.widgets.Canvas.WM_KEYDOWN(Canvas.java:454)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4875)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:359)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5178)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2560)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3815)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:6220)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:394)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:39)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit 523be58.
