### ISSUE TITLE
NPE @ VM20Manipulator.transformSelection():566, v0.8.38b (Log file investigation #1)

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#677]
This affected every call to DatParser.parseLine() and TYPE 1 lines (subparts).

```
java.lang.NullPointerException
	at org.nschmidt.ldparteditor.data.VM20Manipulator.transformSelection(VM20Manipulator.java:566)
	at org.nschmidt.ldparteditor.data.VM20Manipulator.setXyzOrTranslateOrTransform(VM20Manipulator.java:780)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow$185.widgetSelected(Editor3DWindow.java:4293)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:6221)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:394)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:39)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit 1736908.
