### ISSUE TITLE
NPE@getUVcoords() [OpenGL 2.0]

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#699]
```
java.lang.NullPointerException
	at org.nschmidt.ldparteditor.data.GTexture.getUVcoords(GTexture.java:378)
	at org.nschmidt.ldparteditor.data.GData3.drawGL20_BFC_Textured(GData3.java:1174)
	at org.nschmidt.ldparteditor.data.GData1.drawGL20_BFC_Textured(GData1.java:1104)
	at org.nschmidt.ldparteditor.data.GData1.drawGL20_BFC_Textured(GData1.java:1104)
	at org.nschmidt.ldparteditor.data.GDataTEX.drawGL20_BFC_Textured(GDataTEX.java:88)
	at org.nschmidt.ldparteditor.data.DatFile.draw(DatFile.java:255)
	at org.nschmidt.ldparteditor.opengl.OpenGLRenderer20.drawScene(OpenGLRenderer20.java:376)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow$1.run(Editor3DWindow.java:325)
	at org.eclipse.swt.widgets.Display.runTimer(Display.java:4033)
	at org.eclipse.swt.widgets.Display.messageProc(Display.java:3157)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2303)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3532)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:5459)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:422)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:52)
```

Testcase which crashes under Windows and freezes the 3D view under Linux:
```
0 BFC CERTIFY CW

0 !TEXMAP START SPHERICAL 25 5 0 25 5 -5 25 0 -5 360 180 checker.png
0 !: 1 46 25 5 0 5 0 0 0 5 0 0 0 5 48\8-8sphe.dat
0 !TEXMAP FALLBACK
1 46 25 5 0 5 0 0 0 5 0 0 0 5 48\8-8sphe.dat
0 !TEXMAP END

```

**Comment by nilsschmidt1337** [comment]
Closed with commit effbafb.
