### ISSUE TITLE
Unable to launch the program 

### ISSUE THREAD

**Issue by HsueanL** [nilsschmidt1337/ldparteditor#710]
Hi,

I'm running the program on MacOS 10.14 and pre-installed Java SE Runtime Environment 8u201.
When I was trying to launch it, the following error log shows up:

[LDPartEditor RELEASE ] Started on Mon Feb 25 22:54:29 CET 2019
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nschmidt.ldparteditor.workbench.WorkbenchManager.createDefaultWorkbench(WorkbenchManager.java:75)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:113)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:52)
Caused by: org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4537)
	at org.eclipse.swt.SWT.error(SWT.java:4452)
	at org.eclipse.swt.SWT.error(SWT.java:4423)
	at org.eclipse.swt.widgets.Display.error(Display.java:1089)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:840)
	at org.eclipse.swt.widgets.Display.create(Display.java:823)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:129)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:722)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:713)
	at org.eclipse.swt.widgets.Display.getDefault(Display.java:1419)
	at org.eclipse.swt.widgets.Display.lambda$static$0(Display.java:361)
	at org.eclipse.swt.graphics.Device.getDevice(Device.java:71)
	at org.eclipse.swt.graphics.Resource.<init>(Resource.java:49)
	at org.eclipse.swt.graphics.Color.<init>(Color.java:138)
	at org.eclipse.wb.swt.SWTResourceManager.getColor(SWTResourceManager.java:93)
	at org.eclipse.wb.swt.SWTResourceManager.getColor(SWTResourceManager.java:79)
	at org.nschmidt.ldparteditor.enums.Colour.<clinit>(Colour.java:30)
	... 3 more

Is there anything wrong with my side?
Thank you!

**Comment by nilsschmidt1337** [comment]
Hi @HsueanL ,

no, it is a little bit difficult to launch it under MacOS X.
On linux/mac, you have to excecute the shell script "run.sh" to start LDPE.
Open a terminal at the location of the "run.sh" script and execute the command 
`sh run.sh`

You can find a little bit more information on this old wiki page
[https://github.com/nilsschmidt1337/ldparteditor/wiki/home-backup](https://github.com/nilsschmidt1337/ldparteditor/wiki/home-backup)

I am currently re-writing the entire wiki. This takes some time.

Cheers,
Nils
