### ISSUE TITLE
NPE @ VertexWindow

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#720]
```
[LDPartEditor RELEASE 0.8.46 @ SWT v4810 OpenGL 2.0 PLATFORM win32]
java.lang.NullPointerException
	at org.nschmidt.ldparteditor.vertexwindow.VertexWindow.updateVertex(VertexWindow.java:202)
	at org.nschmidt.ldparteditor.vertexwindow.VertexWindow.placeVertexWindow(VertexWindow.java:179)
	at org.nschmidt.ldparteditor.helpers.composite3d.MouseActions.mouseMove(MouseActions.java:254)
	at org.nschmidt.ldparteditor.composites.Composite3D.lambda$76(Composite3D.java:1110)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:5596)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:424)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:52)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit 472fcce.
