### ISSUE TITLE
High colour numbers prevent the colour dialog from showing up.

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#721]
```
java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4467)
	at org.eclipse.swt.SWT.error(SWT.java:4438)
	at org.eclipse.swt.graphics.RGB.<init>(RGB.java:77)
	at org.eclipse.wb.swt.SWTResourceManager.getColor(SWTResourceManager.java:79)
	at org.nschmidt.ldparteditor.dialogs.colour.ColourDesign.addColorButton(ColourDesign.java:175)
	at org.nschmidt.ldparteditor.dialogs.colour.ColourDesign.createContents(ColourDesign.java:152)
	at org.eclipse.jface.window.Window.create(Window.java:426)
	at org.nschmidt.ldparteditor.dialogs.colour.ColourDialog.run(ColourDialog.java:53)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.lambda$263(Editor3DWindow.java:9178)
	at org.nschmidt.ldparteditor.widgets.NButton$1.widgetSelected(NButton.java:154)
	at org.nschmidt.ldparteditor.widgets.NButton.lambda$1(NButton.java:100)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3931)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3534)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:5596)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:424)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:52)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit b4365a0.
