### ISSUE TITLE
Rare error on writing the configuration file when closing the program.

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#738]
Relates to issue #739.

[error_log.txt](https://github.com/nilsschmidt1337/ldparteditor/files/4061456/error_log.txt)
[error_log2.txt](https://github.com/nilsschmidt1337/ldparteditor/files/4061458/error_log2.txt)

```
[ERROR 0.8.48] @org.nschmidt.ldparteditor.workbench.WorkbenchManager
java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(Unknown Source)
	at java.util.zip.InflaterInputStream.read(Unknown Source)
	at java.util.zip.GZIPInputStream.read(Unknown Source)
	at java.io.ObjectInputStream$PeekInputStream.read(Unknown Source)
	at java.io.ObjectInputStream$PeekInputStream.readFully(Unknown Source)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(Unknown Source)
	at java.io.ObjectInputStream.readStreamHeader(Unknown Source)
	at java.io.ObjectInputStream.<init>(Unknown Source)
	at org.nschmidt.ldparteditor.workbench.WorkbenchManager.loadWorkbench(WorkbenchManager.java:87)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:106)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:52)
```

**Comment by nilsschmidt1337** [comment]
It seems that this was dependent from the JDK of the platform.
