### ISSUE TITLE
Log level for argument validation is too high (annotator for comments and TEXMAP)

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#741]
```
[ERROR 0.8.44b] @org.nschmidt.ldparteditor.helpers.compositetext.AnnotatorTexmap
java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4518)
	at org.eclipse.swt.SWT.error(SWT.java:4452)
	at org.eclipse.swt.SWT.error(SWT.java:4423)
	at org.eclipse.swt.custom.StyledText.setSelectionRange(StyledText.java:9777)
	at org.eclipse.swt.custom.StyledText.setSelection(StyledText.java:9680)
	at org.eclipse.swt.custom.StyledText.setSelection(StyledText.java:9601)
	at org.nschmidt.ldparteditor.helpers.compositetext.Annotator.annotate(Annotator.java:87)
	at org.nschmidt.ldparteditor.shells.editortext.EditorTextWindow.lambda$18(EditorTextWindow.java:740)
	at org.nschmidt.ldparteditor.widgets.NButton$1.widgetSelected(NButton.java:154)
	at org.nschmidt.ldparteditor.widgets.NButton.lambda$1(NButton.java:100)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:5459)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:422)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:52)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit 3bd9983.
