### ISSUE TITLE
NPE @ DatParser (subfile has a non existent subfile)

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#742]
```
[ERROR 0.8.44b] @org.nschmidt.ldparteditor.shells.editortext.EditorTextWindow
java.lang.NullPointerException
	at org.nschmidt.ldparteditor.data.GData1.<init>(GData1.java:168)
	at org.nschmidt.ldparteditor.data.GData1.<init>(GData1.java:187)
	at org.nschmidt.ldparteditor.text.DatParser.parse_Reference(DatParser.java:794)
	at org.nschmidt.ldparteditor.text.DatParser.parseLine(DatParser.java:107)
	at org.nschmidt.ldparteditor.data.GData1.<init>(GData1.java:252)
	at org.nschmidt.ldparteditor.text.DatParser.parse_Reference(DatParser.java:794)
	at org.nschmidt.ldparteditor.text.DatParser.parseLine(DatParser.java:107)
	at org.nschmidt.ldparteditor.data.GData1.<init>(GData1.java:252)
	at org.nschmidt.ldparteditor.text.DatParser.parse_Reference(DatParser.java:794)
	at org.nschmidt.ldparteditor.text.DatParser.parseLine(DatParser.java:107)
	at org.nschmidt.ldparteditor.data.GData1.<init>(GData1.java:252)
	at org.nschmidt.ldparteditor.text.DatParser.parse_Reference(DatParser.java:794)
	at org.nschmidt.ldparteditor.text.DatParser.parseLine(DatParser.java:107)
	at org.nschmidt.ldparteditor.data.GData1.<init>(GData1.java:252)
	at org.nschmidt.ldparteditor.text.DatParser.parse_Reference(DatParser.java:794)
	at org.nschmidt.ldparteditor.text.DatParser.parseLine(DatParser.java:107)
	at org.nschmidt.ldparteditor.data.GData1.<init>(GData1.java:252)
	at org.nschmidt.ldparteditor.text.DatParser.parse_Reference(DatParser.java:794)
	at org.nschmidt.ldparteditor.text.DatParser.parseLine(DatParser.java:107)
	at org.nschmidt.ldparteditor.data.GData1.<init>(GData1.java:252)
	at org.nschmidt.ldparteditor.text.DatParser.parse_Reference(DatParser.java:794)
	at org.nschmidt.ldparteditor.text.DatParser.parseLine(DatParser.java:107)
	at org.nschmidt.ldparteditor.data.GData1.<init>(GData1.java:252)
	at org.nschmidt.ldparteditor.text.DatParser.parse_Reference(DatParser.java:794)
	at org.nschmidt.ldparteditor.text.DatParser.parseLine(DatParser.java:107)
	at org.nschmidt.ldparteditor.data.GData1.<init>(GData1.java:252)
	at org.nschmidt.ldparteditor.text.DatParser.parse_Reference(DatParser.java:794)
	at org.nschmidt.ldparteditor.text.DatParser.parseLine(DatParser.java:107)
	at org.nschmidt.ldparteditor.data.GData1.<init>(GData1.java:252)
	at org.nschmidt.ldparteditor.text.DatParser.parse_Reference(DatParser.java:794)
	at org.nschmidt.ldparteditor.text.DatParser.parseLine(DatParser.java:107)
	at org.nschmidt.ldparteditor.data.GData1.<init>(GData1.java:252)
	at org.nschmidt.ldparteditor.text.DatParser.parse_Reference(DatParser.java:794)
	at org.nschmidt.ldparteditor.text.DatParser.parseLine(DatParser.java:107)
	at org.nschmidt.ldparteditor.data.GData1.<init>(GData1.java:252)
	at org.nschmidt.ldparteditor.text.DatParser.parse_Reference(DatParser.java:794)
	at org.nschmidt.ldparteditor.text.DatParser.parseLine(DatParser.java:107)
	at org.nschmidt.ldparteditor.data.GData1.<init>(GData1.java:252)
	at org.nschmidt.ldparteditor.text.DatParser.parse_Reference(DatParser.java:794)
	at org.nschmidt.ldparteditor.text.DatParser.parseLine(DatParser.java:107)
	at org.nschmidt.ldparteditor.data.GData1.<init>(GData1.java:252)
	at org.nschmidt.ldparteditor.text.DatParser.parse_Reference(DatParser.java:794)
	at org.nschmidt.ldparteditor.text.DatParser.parseLine(DatParser.java:107)
	at org.nschmidt.ldparteditor.data.DatFile.parseForData(DatFile.java:1237)
	at org.nschmidt.ldparteditor.composites.compositetab.CompositeTabState.setFileNameObj(CompositeTabState.java:116)
	at org.nschmidt.ldparteditor.shells.editortext.EditorTextWindow.run(EditorTextWindow.java:166)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.openDatFile(Editor3DWindow.java:7372)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.openDatFile(Editor3DWindow.java:7269)
	at org.nschmidt.ldparteditor.shells.editortext.EditorTextWindow.saveAs(EditorTextWindow.java:1276)
	at org.nschmidt.ldparteditor.shells.editortext.EditorTextWindow.lambda$7(EditorTextWindow.java:597)
	at org.nschmidt.ldparteditor.widgets.NButton$1.widgetSelected(NButton.java:154)
	at org.nschmidt.ldparteditor.widgets.NButton.lambda$1(NButton.java:100)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:5459)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:422)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:52)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit 6dd92ce.
