### ISSUE TITLE
Debug-only: NPE @ MemorySnapshot

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#743]
```
java.lang.NullPointerException
	at org.nschmidt.ldparteditor.data.MemorySnapshot.<init>(MemorySnapshot.java:41)
	at org.nschmidt.ldparteditor.data.VM00Snapshot.addSnapshot(VM00Snapshot.java:36)
	at org.nschmidt.ldparteditor.composites.compositetab.CompositeTab$5.modifyText(CompositeTab.java:736)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:34)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit f2ba8dc.
