### ISSUE TITLE
Rare ConcurrentModificationException @ Duplication Check

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#745]
```
[ERROR 0.8.48] @org.nschmidt.ldparteditor.data.DuplicateManager$1
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at java.util.AbstractCollection.addAll(Unknown Source)
	at org.nschmidt.ldparteditor.data.DuplicateManager$1.run(DuplicateManager.java:66)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit 8cf3e7e.
