### ISSUE TITLE
NPE @ readLibraryFolder()

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#750]
LDPE Version 0.8.49b

Caused by: java.lang.NullPointerException
	at org.nschmidt.ldparteditor.data.LibraryManager.readLibraryFolder(LibraryManager.java:713)
	at org.nschmidt.ldparteditor.data.LibraryManager.readUnofficialParts(LibraryManager.java:137)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow$31$1.run(Editor3DWindow.java:5487)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	... 8 more

**Comment by nilsschmidt1337** [comment]
Closed with commit f73501b.
