### ISSUE TITLE
Uncritical NPE @ "Adjust the Manipulator to the Nearest Vertex Position Normal"

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#759]
```
java.lang.NullPointerException
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.mntm_Manipulator_XV_toVertexPosition(Editor3DWindow.java:8255)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.lambda$143(Editor3DWindow.java:2810)
	at org.nschmidt.ldparteditor.widgets.NButton$1.widgetSelected(NButton.java:154)
	at org.nschmidt.ldparteditor.widgets.NButton.lambda$1(NButton.java:100)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3931)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3534)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:5620)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:420)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:52)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit dbd4174.
