### ISSUE TITLE
Uncritical StringIndexOutOfBoundsException @ TextEditor

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#760]
```
java.lang.StringIndexOutOfBoundsException: String index out of range: 43
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:44)
	at java.base/java.lang.String.charAt(String.java:692)
	at org.nschmidt.ldparteditor.composites.compositetab.CompositeTab$8.getPreviousOffset(CompositeTab.java:1375)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:91)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1076)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:775)
	at org.eclipse.swt.custom.StyledText.sendWordBoundaryEvent(StyledText.java:8322)
	at org.eclipse.swt.custom.StyledText.getWordPrevious(StyledText.java:5455)
	at org.eclipse.swt.custom.StyledText.getWordPrevious(StyledText.java:5429)
	at org.eclipse.swt.custom.StyledText.handleMouseDown(StyledText.java:6125)
	at org.eclipse.swt.custom.StyledText.lambda$installListeners$1(StyledText.java:5743)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4118)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1052)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3931)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3534)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Unknown Source)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:420)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:52)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit ed58c2d.
