### ISSUE TITLE
Issue with BFC INVERTNEXT without a following reference line (NPE @ GDataBFC)

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#769]
```
java.lang.NullPointerException
	at org.nschmidt.ldparteditor.data.GDataBFC.drawGL20_BFC(GDataBFC.java:116)
	at org.nschmidt.ldparteditor.data.GDataBFC.drawGL20_WhileAddCondlines(GDataBFC.java:153)
	at org.nschmidt.ldparteditor.data.DatFile.draw(DatFile.java:272)
	at org.nschmidt.ldparteditor.opengl.OpenGLRenderer20.drawScene(OpenGLRenderer20.java:376)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow$1.run(Editor3DWindow.java:336)
	at org.eclipse.swt.widgets.Display.runTimer(Display.java:4033)
	at org.eclipse.swt.widgets.Display.messageProc(Display.java:3157)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2303)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3532)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:5628)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:415)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:52)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit bc4b8c1.
