### ISSUE TITLE
Uncritical NullPointerException on font resource initialization.

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#800]
Version 0.8.52 or older is not affected (tested on Windows and Mac OS X).

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.nschmidt.ldparteditor.enums.View.<clinit>(View.java:287)
	at org.nschmidt.ldparteditor.workbench.UserSettingState.saveColours(UserSettingState.java:823)
	at org.nschmidt.ldparteditor.workbench.WorkbenchManager.saveWorkbench(WorkbenchManager.java:178)
	at org.nschmidt.ldparteditor.workbench.WorkbenchManager.createDefaultWorkbench(WorkbenchManager.java:74)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:111)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:52)
Caused by: java.lang.NullPointerException
	at org.nschmidt.ldparteditor.enums.Font.<clinit>(Font.java:34)
	... 6 more
```

**Comment by nilsschmidt1337** [comment]
Closed with commit b3779cb.
