### ISSUE TITLE
SWTException: Invalid thread access @ clearSelection()

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#83]
[ERROR 0.8.3] @org.nschmidt.ldparteditor.data.VertexManager$22
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.checkWidget(Unknown Source)
	at org.eclipse.swt.widgets.Text.setText(Unknown Source)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.disableSelectionTab(Editor3DWindow.java:6331)
	at org.nschmidt.ldparteditor.data.VertexManager.clearSelection(VertexManager.java:3750)
	at org.nschmidt.ldparteditor.data.VertexManager.selectInverse(VertexManager.java:17773)
	at org.nschmidt.ldparteditor.data.VertexManager.merge(VertexManager.java:19470)
	at org.nschmidt.ldparteditor.data.VertexManager$22.run(VertexManager.java:20408)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:121)

**Comment by nilsschmidt1337** [comment]
Closed with commit 158c546 and 0fcf69b. The solution is now "clean".
