### ISSUE TITLE
NPE @ LibraryManager

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#89]
java.lang.NullPointerException
	at org.nschmidt.ldparteditor.data.LibraryManager.readActualDataFromFolder(LibraryManager.java:1146)
	at org.nschmidt.ldparteditor.data.LibraryManager.syncLibraryFolder(LibraryManager.java:829)
	at org.nschmidt.ldparteditor.data.LibraryManager.syncProjectElements(LibraryManager.java:257)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow$3.widgetSelected(Editor3DWindow.java:341)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at org.nschmidt.ldparteditor.shells.editor3d.Editor3DWindow.run(Editor3DWindow.java:4706)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:298)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:39)

**Comment by nilsschmidt1337** [comment]
Closed with commit 778b6d8.
