### ISSUE TITLE
Strange java.io.FileNotFoundException for "(no file selected)".

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#890]
```
[ERROR 0.8.53] @org.nschmidt.ldparteditor.data.DatFile
java.io.FileNotFoundException: \\(no file selected) (Der angegebene Pfadname ist ungültig)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at org.nschmidt.ldparteditor.text.UTF8BufferedReader.<init>(UTF8BufferedReader.java:45)
at org.nschmidt.ldparteditor.data.DatFile.parseForData(DatFile.java:1149)
at org.nschmidt.ldparteditor.shell.editor3d.Editor3DWindow.openFileIn3DEditor(Editor3DWindow.java:3802)
at org.nschmidt.ldparteditor.shell.editor3d.Editor3DWindow.lambda$run$56(Editor3DWindow.java:1964)
at org.nschmidt.ldparteditor.helper.WUtil$5.widgetSelected(WUtil.java:81)
at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1081)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:780)
at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3193)
at org.eclipse.swt.custom.CTabFolder.destroyItem(CTabFolder.java:808)
at org.eclipse.swt.custom.CTabItem.dispose(CTabItem.java:130)
at org.nschmidt.ldparteditor.shell.editor3d.Editor3DWindow$7.close(Editor3DWindow.java:1941)
at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1956)
at org.eclipse.swt.custom.CTabFolder.lambda$init$0(CTabFolder.java:335)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4175)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3988)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3587)
at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
at org.eclipse.jface.window.Window.open(Window.java:799)
at org.nschmidt.ldparteditor.shell.editor3d.Editor3DWindow.run(Editor3DWindow.java:2027)
at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:412)
at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:48)

[LDPartEditor RELEASE ] Started on Fri Mar 04 19:52:55 CET 2022
[LDPartEditor RELEASE 0.8.53 @ SWT v4930 OpenGL 2.0 PLATFORM win32]
[LDPartEditor RELEASE ] Started on Sat Mar 05 17:01:18 CET 2022
[LWJGL] [MemoryAccessor] Unsupported JVM detected, this will likely result in low performance. Please inform LWJGL developers.
[LDPartEditor RELEASE 1.8.54 @ SWT v4948 OpenGL 2.0 PLATFORM win32]
[ERROR 1.8.54] @org.nschmidt.ldparteditor.data.DatFile
java.io.FileNotFoundException: \\(no file selected) (Der angegebene Pfadname ist ungültig)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(Unknown Source)
at java.base/java.io.FileInputStream.<init>(Unknown Source)
at java.base/java.io.FileInputStream.<init>(Unknown Source)
at org.nschmidt.ldparteditor.text.UTF8BufferedReader.<init>(UTF8BufferedReader.java:45)
at org.nschmidt.ldparteditor.data.DatFile.parseForData(DatFile.java:1149)
at org.nschmidt.ldparteditor.shell.editor3d.Editor3DWindow.openFileIn3DEditor(Editor3DWindow.java:3799)
at org.nschmidt.ldparteditor.shell.editor3d.Editor3DWindow.lambda$run$56(Editor3DWindow.java:1969)
at org.nschmidt.ldparteditor.helper.WUtil$5.widgetSelected(WUtil.java:82)
at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1084)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1069)
at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:773)
at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3248)
at org.eclipse.swt.custom.CTabFolder.destroyItem(CTabFolder.java:812)
at org.eclipse.swt.custom.CTabItem.dispose(CTabItem.java:132)
at org.nschmidt.ldparteditor.shell.editor3d.Editor3DWindow$7.close(Editor3DWindow.java:1946)
at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1961)
at org.eclipse.swt.custom.CTabFolder.lambda$init$0(CTabFolder.java:336)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
at org.eclipse.jface.window.Window.open(Window.java:799)
at org.nschmidt.ldparteditor.shell.editor3d.Editor3DWindow.run(Editor3DWindow.java:2032)
at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:414)
at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:48)

[ERROR 1.8.54] @org.nschmidt.ldparteditor.data.DatFile
java.io.FileNotFoundException: \\(no file selected) (Der angegebene Pfadname ist ungültig)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(Unknown Source)
at java.base/java.io.FileInputStream.<init>(Unknown Source)
at java.base/java.io.FileInputStream.<init>(Unknown Source)
at org.nschmidt.ldparteditor.text.UTF8BufferedReader.<init>(UTF8BufferedReader.java:45)
at org.nschmidt.ldparteditor.data.DatFile.parseForData(DatFile.java:1149)
at org.nschmidt.ldparteditor.shell.editor3d.Editor3DWindow.openFileIn3DEditor(Editor3DWindow.java:3799)
at org.nschmidt.ldparteditor.shell.editor3d.Editor3DWindow.lambda$run$56(Editor3DWindow.java:1969)
at org.nschmidt.ldparteditor.helper.WUtil$5.widgetSelected(WUtil.java:82)
at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1084)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1069)
at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:773)
at org.eclipse.swt.custom.CTabFolder.setSelection(CTabFolder.java:3248)
at org.eclipse.swt.custom.CTabFolder.destroyItem(CTabFolder.java:812)
at org.eclipse.swt.custom.CTabItem.dispose(CTabItem.java:132)
at org.nschmidt.ldparteditor.shell.editor3d.Editor3DWindow$7.close(Editor3DWindow.java:1946)
at org.eclipse.swt.custom.CTabFolder.onMouse(CTabFolder.java:1961)
at org.eclipse.swt.custom.CTabFolder.lambda$init$0(CTabFolder.java:336)
at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
at org.eclipse.jface.window.Window.open(Window.java:799)
at org.nschmidt.ldparteditor.shell.editor3d.Editor3DWindow.run(Editor3DWindow.java:2032)
at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:414)
at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:48) 
```

**Comment by nilsschmidt1337** [comment]
Closed with commit 76d4ff8.
