### ISSUE TITLE
Integrate lwjgl3-swt, a revised drop-in implementation of SWT's GLCanvas.

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#896]
https://github.com/LWJGLX/lwjgl3-swt
[lwjgl3-swt-main.zip](https://github.com/nilsschmidt1337/ldparteditor/files/8566717/lwjgl3-swt-main.zip)

**Comment by nilsschmidt1337** [comment]
Currently, [lwjgl3-swt](https://github.com/LWJGLX/lwjgl3-swt) is not compatible with SWT 4.22 on Linux, it requires 3.113.0.
```
Exception in thread "main" java.lang.NoSuchMethodError: 'long org.eclipse.swt.internal.gtk.GTK.gtk_widget_get_window(long)'
	at org.lwjgl.opengl.swt.PlatformLinuxGLCanvas.create(PlatformLinuxGLCanvas.java:56)
	at org.lwjgl.opengl.swt.GLCanvas.<init>(GLCanvas.java:73)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:168)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:48)
```
