### ISSUE TITLE
Error while creating a subfile from 3D selection

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#904]
```
java.lang.NullPointerException: Cannot invoke "org.nschmidt.ldparteditor.data.GData.type()" because "g" is null
	at org.nschmidt.ldparteditor.data.VM99Clipboard.extendClipboardContent(VM99Clipboard.java:842)
	at org.nschmidt.ldparteditor.data.VertexManager.extendClipboardContent(VertexManager.java:1)
	at org.nschmidt.ldparteditor.shell.editor3d.toolitem.AddToolItem.lambda$2(AddToolItem.java:203)
	at org.nschmidt.ldparteditor.widget.NButton$1.widgetSelected(NButton.java:124)
	at org.nschmidt.ldparteditor.widget.NButton.mouseDown(NButton.java:146)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4243)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1060)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4060)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3632)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at org.nschmidt.ldparteditor.shell.editor3d.Editor3DWindow.run(Editor3DWindow.java:2037)
	at org.nschmidt.ldparteditor.splash.SplashScreen.run(SplashScreen.java:414)
	at org.nschmidt.ldparteditor.main.LDPartEditor.main(LDPartEditor.java:48)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit [864db62](https://github.com/nilsschmidt1337/ldparteditor/commit/864db62fa3e62de3c59b681fec1f9d654a2e004c).
