### ISSUE TITLE
Uncritical NullPointerException @ DatHeaderManager (while checking the header for errors)

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#973]
This was uncritical because the thread for checking the header can be restarted:
```
[ERROR 1.8.69] @org.nschmidt.ldparteditor.data.DatHeaderManager
java.lang.NullPointerException: Cannot read field "next" because "gd" is null
	at org.nschmidt.ldparteditor.data.DatHeaderManager.checkDatHeader(DatHeaderManager.java:598)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by nilsschmidt1337** [comment]
Closed with commit #973.
