### ISSUE TITLE
Improve exception logging for FileNotFoundException when accessing library.ldraw.org.

### ISSUE THREAD

**Issue by nilsschmidt1337** [nilsschmidt1337/ldparteditor#975]
```
[ERROR 1.8.68] @org.nschmidt.ldparteditor.helper.FileHelper
java.io.FileNotFoundException: https://library.ldraw.org/library/unofficial/p/4-4cylc.dat
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1993)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at org.nschmidt.ldparteditor.helper.FileHelper.downloadPartFile(FileHelper.java:125)
	at org.nschmidt.ldparteditor.shell.editor3d.toolitem.MiscToolItem$4.buildFileList(MiscToolItem.java:1888)
	at org.nschmidt.ldparteditor.shell.editor3d.toolitem.MiscToolItem$4.buildFileList(MiscToolItem.java:1897)
	at org.nschmidt.ldparteditor.shell.editor3d.toolitem.MiscToolItem$4$1.run(MiscToolItem.java:1663)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
```

should display this instead (and with debug log level instead of error log level):

```
[DEBUG 1.8.68] @org.nschmidt.ldparteditor.helper.FileHelper: Can't find https://library.ldraw.org/library/unofficial/p/4-4cylc.dat
```

**Comment by nilsschmidt1337** [comment]
Closed with commit [6e4e103](https://github.com/nilsschmidt1337/ldparteditor/commit/6e4e103c74cb378fae7aeef708a3d6cdf08f180a).
